[package]
name = "mapreduce"
version = "0.1.14"
edition = "2021"
description = "High-performance distributed MapReduce engine in Rust"
license = "MIT"
exclude = [
    "benchmarks/**/*",
    "dataset/**/*",
    "pymapreduce/**/*",
    "tests/**/*",
    "testing/**/*",
    "*.md",
    ".vscode/**/*",
    "clippy.txt",
    "*.tex",
    "Dockerfile",
    "docker-compose.yml",
]

[lib]
name = "mapreduce"
path = "src/lib.rs"

[[bin]]
name = "mapreduce"
path = "src/main.rs"

[dependencies]
# Async runtime
tokio      = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }

# Serialization
serde      = { version = "1", features = ["derive"] }
bincode    = "1"
bytes      = "1"

# Error handling
thiserror  = "2"
anyhow     = "1"

# Concurrency
dashmap    = "6"         # lock-free HashMap cho ObjectStore hot tier
parking_lot = "0.12"     # faster RwLock

# System
sysinfo    = "0.32"      # CPU/RAM detection
num_cpus   = "1"         # physical core count

# Object store
memmap2    = "0.9"       # mmap cho warm tier

# CLI
clap       = { version = "4", features = ["derive", "env"] }

# Logging
tracing              = "0.1"
tracing-subscriber   = { version = "0.3", features = ["env-filter"] }

# IDs & time
uuid    = { version = "1", features = ["v4", "serde"] }
chrono  = { version = "0.4", features = ["serde"] }
zip     = "2.2.0"

# Async streams (cho ObjectRef::stream())
futures = "0.3"
async-trait = "0.1"
